jobs:
  - name: generate-manifest
    type: manifest
    steps:
      - GET scriptnull-sample-node
      - GET large-container

  - name: deploy-service
    type: ecsDeploy
    steps:
      - GET generate-manifest
      - GET scriptnull-ecs-cluster
  
