jobs:
  - name: generate-manifest
    type: manifest
    steps:
      - GET scriptnull-busybox
      - GET small-container
      - GET large-container
      - PUT large-container

  # - name: deploy-service
  #   type: ecsDeploy
  #   steps:
  #     - GET generate-manifest
  #     - GET scriptnull-ecs-cluster
  # Please work
