jobs:
  - name: generate-manifest
    type: manifest
    steps:
      - GET: scriptnull-node
      - GET: scriptnull-params

  - name: scriptnull-deploy
    type: dclDeploy
    steps:
      - GET: generate-manifest
      - GET: scriptnull-dcl-cluster

  - name: hello
    type: manifest
    steps:
      - GET: xxx
