jobs:
  - name : super-job
    type : manifest
    steps :
      - GET: super-container

  - name : error-job
    type : manifest
    steps :
      - GET: ultra-small-container

  - name : sorry-job
    type : manifest
    steps :
      - GET: yo-container
