jobs:
  - name: tri-manifest
    type: manifest
    steps:
      - GET: tri-sn
      # - DO: tri-nginx

  - name: tri-deploy
    type: tripubDeploy
    steps:
      - GET: tri-manifest
      - GET: tri-cluster
    
