jobs:
  - job:
      name : job1
      type: manifest
      steps:
        - GET resource1

  - job:
      name : job2
      type: manifest
      steps:
        - GET resource1

  - job:
      name : job3
      type: manifest
      steps:
        - GET resource1

  - job:
      name : job4
      type: manifest
      steps:
        - GET resource1
