jobs:
  - name: dv-man
    type: manifest
    steps:
      - GET: dv-image
      - GET: dv-opts
      - GET: dv-params

  - name: dv-man-delete
    type: manifest
    steps:
      - GET: dv-image
      - GET: dv-opts
      - GET: dv-params
