jobs:
  - name: tri-manifest-1
    type: manifest
    steps:
      - GET: tri-nginx-1
      # - DO: tri-nginx

  - name: tri-deploy-1
    type: tripubDeploy
    steps:
      - GET: tri-manifest-1
      - GET: tri-cluster-1
    
