jobs:
  - name: xx-generate-manifest
    type: manifest
    steps:
      - GET: scriptnull-busybox
      - GET: large-container

  - name: xx-deploy-service
    type: ecsDeploy
    steps:
      - GET: xx-generate-manifest
      - GET: scriptnull-ecs-cluster
  
