jobs:
  - name: tri-manifest
    type: manifest
    steps:
      - GET: tri-sn
      # - DO: tri-nginx

  - name: tri-deploy
    type: tripubDeploy
    steps:
      - GET: tri-manifest
      - GET: tri-cluster
      - GET: tri-ecs-deploy
    
  - name: tri-ecs-manifest
    type: manifest
    steps:
      - GET: tri-nginx

  - name: tri-ecs-deploy
    type:  ecsDeploy
    steps:
      - GET: tri-ecs-manifest
      - GET: tri-ecs-cluster
