jobs:
  - name: sn-man
    type: manifest
    steps:
      - GET: sn-nginx
      - GET: sn-trigger
      # - GET: sn-opts
      # - GET: sn-replicas

  - name: x1-gke
    type: gkeDeploy
    steps:
      - GET: sn-man
      - GET: sn-gke
