jobs:
  - name: x-tripub-manifest
    type: manifest
    steps:
      - GET: sn-nginx
      - GET: x-tripub-trigger

  - name: x-tripub-deploy
    type: tripubDeploy
    options:
      deployMethod: upgrade
    steps:
      - GET: x-tripub-manifest
      - GET: x-tripub-super-cluster

  # - name: x-ecs-manifest
  #   type: manifest
  #   steps:
  #     - GET: sn-ecs-nginx
  #     - GET: x-ecs-trigger
  #
  # - name: x-ecs-deploy
  #   type: ecsDeploy
  #   options:
  #     deployMethod: blueGreen
  #   steps:
  #     - GET: x-ecs-manifest
  #     - GET: x-ecs-cluster
