triggers:
  - name: sn-trigger-2
    type: trigger
    pointer:
      counter: 8

  - name: sn-trigger-3
    type: trigger
    pointer:
      counter: 2

  - name: runTrigger
    type: trigger
    pointer:
      counter: 2
