jobs:
  - name: bfri-man-1
    type: manifest
    steps:
      - IN: sn-driftking
      - IN: sn-replicas
      - IN: bfri-trigger-1

  - name: bfri-deploy-1
    type: deploy
    steps:
      - IN: lfri-man-1
      - IN: tripub-cluter

  # - name: bmon-tri-man
  #   type: manifest
  #   steps:
  #     - IN: sn-sn
  #     - IN: bmon-tri-trigger
  #
  # - name: bmon-tri-deploy
  #   type: deploy
  #   steps:
  #     - IN: bmon-tri-man
  #     - IN: tripub-cluter
  #
  # - name: up-bmon-tri-deploy
  #   type: deploy
  #   steps:
  #     - IN: bmon-tri-man
  #     - IN: tripub-cluter
  #     - TASK: managed
  #       deployMethod: upgrade

  # - name: bmon-dcl-man
  #   type: manifest
  #   steps:
  #     - IN: sn-sn
  #     - IN: bmon-dcl-trigger
  #
  # - name: bmon-dcl-deploy
  #   type: deploy
  #   steps:
  #     - IN: bmon-dcl-man
  #     - IN: dcl-cluter


  # - name: old-tri-man
  #   type: manifest
  #   steps:
  #     - IN: sn-entrypoint
  #     - IN: old-tri-trigger
  #
  # - name: old-tri-deploy
  #   type: tripubDeploy
  #   steps:
  #     - IN: old-tri-man
  #     - IN: tripub-cluter
