triggers:
  - name: sn-b-trigger
    type: trigger
    version:
      counter: 5

  - name: sn-b-tri-trigger
    type: trigger
    version:
      counter: 0

  - name: sn-b-ddc-trigger
    type: trigger
    version:
      counter: 0

  - name: sn-b-gke-trigger
    type: trigger
    version:
      counter: 0

  - name: sn-b-ecs-trigger
    type: trigger
    version:
      counter: 0

  - name: sn-b-dcl-trigger
    type: trigger
    version:
      counter: 2

  - name: sn-b-mix-trigger
    type: trigger
    version:
      counter: 5
