jobs:
  - name: sn-b1-man-1
    type: manifest
    steps:
      - IN: sn-b1-myapp2
      - IN: sn-b1-trigger

  - name: fail-runSh
    type: runSh
    steps:
      - IN: sn-b1-script-repo
      - IN: sn-b1-runTrigger
      - TASK:
        - script: /build/IN/sn-b1-script-repo/gitRepo/fail.sh

  - name: sn-b1-ecs-deploy
    type: deploy
    steps:
      - IN: sn-b1-man-1
      - IN: sn-ecs-testCL
      - TASK: managed
        deployMethod: upgrade
