jobs:
  - name: b-monddc-1-man
    type: manifest
    steps:
      - IN: sn-nginx
      - IN: b-ddc-trigger
      - TASK: managed

  - name: mon-ddc
    type: ddcDeploy
    steps:
      - IN: b-monddc-1-man
      - IN: gen-ddc-cluster
      - TASK: managed
