triggers:
  - name: sn-trigger
    type: trigger
    pointer:
      counter: 6

  - name: ecs-trigger
    type: trigger
    pointer:
      counter: 6

  - name: tri-trigger
    type: trigger
    pointer:
      counter: 2
