triggers:
  - name: sn-b-trigger
    type: trigger
    version:
      counter: 13

  - name: sn-b-tm-trigger
    type: trigger
    version:
      counter: 10

  - name: sn-b-ddc-trigger
    type: trigger
    version:
      counter: 15

  - name: sn-b-gke-trigger
    type: trigger
    version:
      counter: 6

  - name: sn-b-ecs-trigger
    type: trigger
    version:
      counter: 15

  - name: sn-b-dcl-trigger
    type: trigger
    version:
      counter: 1
