triggers:
  - name: triggertest1
    type: trigger
    source:
      message: 'testing trigger in yml'

  - name: triggertest2
    type: trigger
    source:
      counter: 72

  - name: triggertest3
    type: trigger
    source:
      counter: 1
