jobs:
  # - name: sn-aq-man-jfrog
  #   type: manifest
  #   steps:
  #     - IN: sn-aq-file-jfrog
      # - IN: sn-aq-file

  # - name: sn-aq-file-deploy
  #   type: deploy
  #   steps:
  #     - IN: sn-aq-man-jfrog
  #     - IN: sn-aq-cluster

  # - name: sn-aq-file-man-9
  #   type: manifest
  #   steps:
  #     - IN: sn-aq-file
      # - IN: sn-aq-params
      # - IN: sn-aq-vici-http-js
      # - IN: sn-aq-file-trigger
      # - name: sn-aq-vici-man

  #   type: manifest
  #   steps:
  #     - IN: sn-aq-vici-http-js
  #     - IN: sn-aq-file-man
  #     - IN: sn-aq-vici-trigger

  # - name: sn-aq-cluster-dep-9
  #   type: deploy
  #   steps:
  #     - IN: sn-aq-file-man-9
  #     - IN: sn-aq-cluster
  #     - TASK:
  #         - script: xkcd

  # - name: sn-aq-tri-man
  #   type: manifest
  #   steps:
  #     - IN: sn-aq-private-image
  #     - IN: sn-aq-tm-trigger

  # - name: sn-aq-tri-dep-1
  #   type: deploy
  #   steps:
  #     - IN: sn-aq-tri-man
  #     - IN: sn-aq-tri-cluster

  # - name: sn-aq-tri-dep-upgrade
  #   type: deploy
  #   steps:
  #     - IN: sn-aq-tri-man
  #     - IN: sn-aq-scaler
  #     - IN: sn-aq-tri-cluster
  #     - TASK: managed
  #       deployMethod: upgrade

  # - name: sn-aq-tri-dep-replace
  #   type: deploy
  #   steps:
  #     - IN: sn-aq-tri-man
  #     - IN: sn-aq-tri-cluster
  #     - TASK: managed
  #       deployMethod: replace

  - name: sn-aq-gke-man
    type: manifest
    steps:
      - IN: sn-aq-dk
      - IN: sn-aq-docker-opts-1
      - IN: sn-aq-gke-trigger

  - name: sn-aq-gke-dep
    type: deploy
    steps:
      - IN: sn-aq-gke-man
      - IN: sn-aq-gke-cluster

  - name: sn-aq-ddc-man
    type: manifest
    steps:
      - IN: sn-aq-dk
      - IN: sn-aq-docker-opts-1
      - IN: sn-aq-ddc-trigger

  - name: sn-aq-ddc-dep
    type: deploy
    steps:
      - IN: sn-aq-ddc-man
      - IN: sn-aq-ddc-cluster

  - name: sn-aq-ecs-man
    type: manifest
    steps:
      - IN: sn-aq-dk
      - IN: sn-aq-docker-opts-1
      - IN: sn-aq-ecs-trigger

  - name: sn-aq-ecs-dep
    type: deploy
    steps:
      - IN: sn-aq-ecs-man
      - IN: sn-aq-ecs-cluster

  # - name: sn-aq-ecs-lb-man
  #   type: manifest
  #   steps:
  #     - IN: sn-aq-ep
  #     - IN: sn-aq-dk
  #     - IN: sn-aq-ecs-lb-trigger
  #
  # - name: sn-aq-ecs-lb-deploy
  #   type: deploy
  #   steps:
  #     - IN: sn-aq-ecs-lb-man
  #     - IN: sn-aq-ecs-lb-cluster
  #     - IN: lb-loadbalancer1
  #       applyTo:
  #         - manifest: sn-aq-ecs-lb-man
  #           image: sn-aq-dk
  #         - manifest: sn-aq-ecs-lb-man
  #           image: sn-aq-ep
  #         - manifest: sn-aq-ecs-lb-man
  #           image: sn-aq-myapp3
  #     - TASK: managed
  #       deployMethod: upgrade
  #
  # - name: sn-aq-mix-a-man
  #   type: manifest
  #   steps:
  #     - IN: sn-aq-ep
  #     - IN: sn-aq-mix-a-trigger
  #
  # - name: sn-aq-mix-b-man
  #   type: manifest
  #   steps:
  #     - IN: sn-aq-ep
  #     - IN: sn-aq-mix-b-trigger

  # - name: sn-aq-multi-manifest-gke
  #   type: deploy
  #   steps:
  #     - IN: sn-aq-mix-a-man
  #       force: true
  #     - IN: sn-aq-mix-b-man
  #       force: true
  #     - IN: sn-aq-gke-cluster
  #     - TASK: managed
  #       deployOptions:
  #         - parallel
