triggers:
  - name: sn-trigger
    type: trigger
    pointer:
      counter: 7

  - name: ecs-trigger
    type: trigger
    pointer:
      counter: 6

  - name: tri-trigger
    type: trigger
    pointer:
      counter: 2

  - name: fb-trigger
    type: trigger
    pointer:
      counter: 5
