triggers:
  - name: sn-trigger-2
    type: trigger
    version:
      counter: 10

  - name: sn-trigger-3
    type: trigger
    version:
      counter: 2

  - name: tri-trigger
    type: trigger
    version:
      counter: 3

  - name: runTrigger
    type: trigger
    version:
      counter: 2

  - name: good-runTrigger
    type: trigger
    version:
      counter: 3
