jobs:
  - name: b-th-manifest
    type: manifest
    steps:
      - IN: sn-driftking
      - IN: sn-opts
      - IN: b-thursday-trigger
      - TASK: managed

  - name: b-th-deploy
    type: tripubDeploy
    steps:
      - IN: b-th-manifest
      - IN: tripub-cluter
      - TASK: managed
