jobs:
  - name: sn-b-man-1
    type: manifest
    steps:
      - IN: sn-myapp3-1
      - IN: sn-trigger-2

  - name: sn-b-invalid-man
    type: manifest
    steps:
      - IN: sn-myapp3-1

  - name: sn-b-man-2
    type: manifest
    steps:
      - IN: sn-myapp3-1
      - IN: sn-docker-opts-1
      - IN: sn-trigger-3

  - name: sn-b-man-3
    type: manifest
    steps:
      - IN: sn-myapp3-1
      - IN: sn-tri-do
      - IN: tri-trigger

  - name: fail-runSh
    type: runSh
    steps:
      - IN: script-repo
      - IN: runTrigger
      - TASK:
        - script: /build/IN/script-repo/gitRepo/fail.sh

  - name: good-runSh
    type: runSh
    steps:
      - IN: sn-myapp3-1
      - IN: good-runTrigger
      - TASK:
          - script: echo "starting ..."
          - script: "echo 'versionName=latest' > /build/state/sn-myapp2-1.env"
      - OUT: sn-myapp2-1

  - name: sn-ecsDeploy-5
    type: deploy
    steps:
      - IN: sn-b-man-1
      - IN: sn-ecs-cluster-1
      - TASK: managed
        deployMethod: upgrade

  - name: sn-ecsDeploy-5
    type: deploy
    steps:
      - IN: sn-b-man-2
      - IN: sn-ecs-cluster-1
      # - IN: sn-lb
      #   applyTo:
      #     - manifest: sn-b-man-1 # it can only apply to one manifest
      #       image: sn-myapp3-1 # it can only apply to one image in the manifest
      #       port: 80

  - name: sn-tri-deploy
    type: deploy
    steps:
      - IN: sn-b-man-3
      - IN: sn-tri-cluster

  - name: b-invalid-runSh
    type: runSh
    steps:
      - TASK:
        - script: ls

  - name: b-invalid-release
    type: release
    steps:
      - IN: sn-b-invalid-man

  # - name: invalid-rSync
  #   type: rSync
  #   steps:
  #     - IN: sn-b-man-3

  - name: sn-b-delete
    type: manifest
    steps:
      - IN: sn-myapp3-1
      - IN: sn-trigger-delete

  # - name: sn-ecs-del-1
  #   type: deploy
  #   steps:
  #     - IN:  sn-b-delete
  #     - IN: sn-ecs-cluster-1

  - name: sn-ecs-del-2
    type: deploy
    steps:
      - IN: sn-b-delete
      - IN: sn-ddc-cluster
