jobs:
  - name: sn-man
    type: manifest
    steps:
      - GET: sn-sn-1
      - GET: triggertest2
      # - GET: sn-opts
      # - GET: sn-replicas

  - name: micro-job
    type: gkeDeploy
    options:
      deployMethod: blueGreen
    steps:
      - GET: sn-man
      - GET: sn-micro-gke


  # - name: sn-gke-deploy
  #   type: gkeDeploy
  #   steps:
  #     - GET: sn-man
  #     - GET: sn-gke

  # - name: bg-gke
  #   type: gkeDeploy
  #   options:
  #     deployMethod: blueGreen
  #   steps:
  #     - GET: sn-man
  #     - GET: sn-gke
