jobs:
  - name: tri-manifest-A
    type: manifest
    steps:
      - GET: tri-sn

  - name: tri-manifest-B
    type: manifest
    steps:
      - GET: tri-nginx

  - name: tri-deploy
    type: tripubDeploy
    steps:
      - GET: tri-manifest-A
      - GET: tri-cluster
    
