triggers:
  # - name: sn-aq-file-trigger
  #   type: trigger
  #   version:
  #     counter: 12
  #
  # - name: sn-aq-vici-trigger
  #   type: trigger
  #   version:
  #     counter: 2

  # - name: sn-aq-trigger-1
  #   type: trigger
  #   version:
  #     counter: 43
  #
  # - name: sn-aq-tm-trigger
  #   type: trigger
  #   version:
  #     counter: 24
  #
  - name: sn-aq-ddc-trigger
    type: trigger
    version:
      counter: 19
  #
  - name: sn-aq-gke-trigger
    type: trigger
    version:
      counter: 13
  #
  - name: sn-aq-ecs-trigger
    type: trigger
    version:
      counter: 4

  # - name: sn-aq-ecs-lb-trigger
  #   type: trigger
  #   version:
  #     counter: 15
  #
  # - name: sn-aq-mix-a-trigger
  #   type: trigger
  #   version:
  #     counter: 4
  #
  # - name: sn-aq-mix-b-trigger
  #   type: trigger
  #   version:
  #     counter: 7
