jobs:
  - name: sn-b-dcl-man
    type: manifest
    steps:
      - IN: sn-b-dk
      - IN: sn-b-trigger

  - name: sn-b-dcl-dep
    type: deploy
    steps:
      - IN: sn-b-dcl-man
      - IN: sn-b-dcl-cluster
