jobs:
  - name: sn-b-man-1
    type: manifest
    steps:
      - IN: sn-b-ep
      - IN: sn-b-docker-opts-1
      - IN: sn-b-trigger-1

  - name: sn-b-ecs-deploy
    type: deploy
    steps:
      - IN: sn-b-man-1
      - IN: sn-b-ddc-cluster

  - name: sn-b-tri-man
    type: manifest
    steps:
      - IN: sn-b-ep
      - IN: sn-b-tm-trigger

  - name: sn-b-tri-dep
    type: deploy
    steps:
      - IN: sn-b-tri-man
      - IN: sn-b-tri-cluster
