##################### GKE Testing starts here
jobs:
  # - name: fl-man
  #   type: manifest
  #   steps:
  #     - GET: sn-nginx
  #     - GET: fl-trigger
  #     - TASK: managed
  #
  # - name: fl-gke
  #   type: gkeDeploy
  #   steps:
  #     - GET: fl-man
  #     - GET: sn-gke
  #     - TASK: managed
  #       deployMethod: upgrade

  # - name: slbg-1-man
  #   type: manifest
  #   steps:
  #     - GET: sn-nginx
  #     - GET: slbg-trigger
  #     - TASK: managed
  #
  # - name: slbg-2-man
  #   type: manifest
  #   steps:
  #     - GET: sn-sn
  #     - GET: slbg-trigger
  #     - TASK: managed
  #
  # - name: slbg-gke
  #   type: gkeDeploy
  #   steps:
  #     - GET: slbg-1-man
  #     - GET: slbg-2-man
  #     - GET: sn-gke
  #     - TASK: managed
  #       deployMethod: blueGreen

  - name: sbbg-1-man
    type: manifest
    steps:
      - GET: sn-sn
      - GET: sbbg-trigger
      - TASK: managed

  - name: sbbg-2-man
    type: manifest
    steps:
      - GET: sn-nginx
      - GET: sbbg-trigger
      - TASK: managed

  - name: sbbg-gke
    type: gkeDeploy
    steps:
      - GET: sbbg-1-man
      - GET: sbbg-2-man
      - GET: sn-gke
      - TASK: managed
        deployMethod: upgrade

#################################

  - name: sbup-1-man
    type: manifest
    steps:
      - GET: sn-sn
      - GET: sbup-trigger
      - TASK: managed

  - name: sbup-2-man
    type: manifest
    steps:
      - GET: sn-nginx
      - GET: sbup-trigger
      - TASK: managed

  - name: sbup-gke
    type: gkeDeploy
    steps:
      - GET: sbup-1-man
      - GET: sbup-2-man
      - GET: sn-gke
      - TASK: managed
        deployMethod: upgrade


  # - name: flbg-man
  #   type: manifest
  #   steps:
  #     - GET: sn-nginx
  #     - GET: flbg-trigger
  #     - TASK: managed
  #
  # - name: flbg-gke
  #   type: gkeDeploy
  #   steps:
  #     - GET: flbg-man
  #     - GET: sn-gke
  #     - TASK: managed

  # - name: flsm-man
  #   type: manifest
  #   steps:
  #     - GET: sn-sn
  #     - GET: flsm-trigger
  #     - TASK: managed
  #
  # - name: flsm-gke
  #   type: gkeDeploy
  #   steps:
  #     - GET: flsm-man
  #     - GET: sn-small-gke
  #     - TASK: managed
  #       deployType: blueGreen

  # - name: 1-man
  #   type: manifest
  #   steps:
  #     - GET: sn-sn
  #     - GET: x-trigger
  #
  # - name: 2-man
  #   type: manifest
  #   steps:
  #     - GET: sn-nginx
  #     - GET: x-trigger
  #
  # - name: multi-gke
  #   type: gkeDeploy
  #   options:
  #     deployMethod: blueGreen
  #   steps:
  #     - GET: 1-man
  #     - GET: 2-man
  #     - GET: sn-gke
