jobs:
  - name: bmon-tri-man
    type: manifest
    steps:
      - IN: sn-nginx
      - IN: bmon-tri-trigger

  - name: bmon-tri-deploy
    type: deploy
    steps:
      - IN: bmon-tri-man
      - IN: tripub-cluter

  # - name: old-tri-man
  #   type: manifest
  #   steps:
  #     - IN: sn-entrypoint
  #     - IN: old-tri-trigger
  #
  # - name: old-tri-deploy
  #   type: tripubDeploy
  #   steps:
  #     - IN: old-tri-man
  #     - IN: tripub-cluter
