jobs:
  - name: sn-b-man-1
    type: manifest
    steps:
      - IN: sn-b-dk
      - IN: sn-b-docker-opts-1
      - IN: sn-b-trigger-1

  - name: sn-b-ecs-deploy
    type: deploy
    steps:
      - IN: sn-b-man-1
      - IN: sn-b-ddc-cluster
