triggers:
  - name: sn-trigger-2
    type: trigger
    pointer:
      counter: 9

  - name: sn-trigger-3
    type: trigger
    pointer:
      counter: 2

  - name: tri-trigger
    type: trigger
    pointer:
      counter: 3

  - name: runTrigger
    type: trigger
    pointer:
      counter: 2
